### ISSUE TITLE
Importer casting exception

### ISSUE THREAD

**Issue by gorankarabeg** [ardoq/ardoq-net-importer#2]
Hi guys, Good work, 

I have been able to compile the solution after I excluded Ardoq project from the solution and added nuget pack for ardoq for 3 projects. But then 
I am trying to use this tool to generate documentation and exception is thrown like below.

```
 ardoq-cecil-inspection.exe -t "my-token" -a "path-to-dll"
Connecting to: https://app.ardoq.com
 - : ardoq
Missing model, creating default model.
Parsing model: "name": ".Net"

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type Ardoq.Models.Workspace. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'description', line 1, position 15.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass2e`1.<<buildCancellableTaskFuncForMethod>b__2d>d__30.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ardoq.Util.SyncRepository.<CreateWorkspace>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Ardoq.Util.SyncRepository.<PrefetchWorkspace>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ardoq.CommandRunner.<Run>d__5.MoveNext() in C:\Dev\code\ardoq-net-importer-master\ardoq-net-importer-master\ardoq-cecil-inspection\CommandRunner.cs:line 60
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Ardoq.Program.Main(String[] args) in C:\Dev\code\ardoq-net-importer-master\ardoq-net-importer-master\ardoq-cecil-inspection\Program.cs:line 27
```

**Comment by kristianhelgesen** [comment]
Hi, we just released an update to our API, and we missed this application in the process. I'll work on a fix as soon as possible, and get back to you.

**Comment by kristianhelgesen** [comment]
It looks like this project assumes that the project https://github.com/ardoq/ardoq-csharp-client is checked out next to this project. The nuget package should also work (in version 1.4.0)
Could you try checking out both projects and trying again?

**Comment by gorankarabeg** [comment]
I used nuget pacakage. It builds fine but running with the token and dll filepath specified still throws the same JsonSerializationException. If I use the code as you mentioned then I get another exception when running the command:

```
λ ardoq-cecil-inspection.exe -t "my-token" -a "path-to-dll"
Connecting to: https://app.ardoq.com
 - : ardoq


Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Refit.ApiException: Response status code does not indicate success: 500 (Internal Server Error).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass2e`1.<<buildCancellableTaskFuncForMethod>b__2d>d__30.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 326
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ardoq.CommandRunner.<SetupArdoqClient>d__7.MoveNext() in C:\Dev\code\ardoq-net-importer\ardoq-cecil-inspection\CommandRunner.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ardoq.CommandRunner.<Run>d__5.MoveNext() in C:\Dev\code\ardoq-net-importer\ardoq-cecil-inspection\CommandRunner.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Ardoq.Program.Main(String[] args) in C:\Dev\code\ardoq-net-importer\ardoq-cecil-inspection\Program.cs:line 27
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ardoq.CommandRunner.<Run>d__5.MoveNext() in C:\Dev\code\ardoq-net-importer\ardoq-cecil-inspection\CommandRunner.cs:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Ardoq.Program.Main(String[] args) in C:\Dev\code\ardoq-net-importer\ardoq-cecil-inspection\Program.cs:line 27
```
